- Cargo.toml
- src/x25519.rs
Fixes #5 (allows x25519-dalek to compile on stable).
informed by https://github.com/dalek-cryptography/curve25519-dalek/commit/6748dddb96897b9cf9d5ea8df0fdf5e6f14e654d:
- sub `CompressedMontgomeryU` with `MontgomeryPoint`, removing
(de)compress calls.
informed by https://github.com/dalek-cryptography/curve25519-dalek/commit/d32fe9772b296511638f662da75b71a41bc61eb6:
- sub `Scalar([u8; 32])` with `Scalar::from_bits([u8; 32])`
This diff also ups the rand version since it was old, but that's independent of all the other changes.
And as an added bonus, handshake benchmarks in wireguard-rs are 15% faster with this version of x25519-dalek :).
> Use latest curve25519-dalek.

- Cargo.toml
0.5 is finally out of prerelease purgatory 🎉
> use production rand 0.5 release

- Cargo.toml
- README.md
- benches/x25519.rs
- src/lib.rs
- src/x25519.rs
PR for issue #9 
Created `Ephemeral` & `SharedSecret` types to use for keys. 
`diffie_hellman`, `generate_public`, & `generate_secret` are now methods on `Ephemeral`. 
Both types use `clear` in their respective `drop` implementations & `Ephemeral` has an implementation for `Mul`.
> Create new types for keys and clear values on drop

- Cargo.toml
- README.md
- benches/x25519.rs
- src/lib.rs
This PR switches from thread rng to OS RNG in examples, but I think it's a good default.
> Use rand_os instead of rand

- Cargo.toml
This fixes https://github.com/dalek-cryptography/x25519-dalek/issues/23 as
reported by @DebugSteven.
> Fix link to now-missing katex header.

- .travis.yml
- README.md
- benches/x25519.rs
- src/x25519.rs
Currently, the API uses only ephemeral secret keys for Diffie-Hellman & everything else is forced to use the bare `x25519` function.
This PR implements another secret key type. We have two secret key types, 'EphemeralSecret' & 'StaticSecret', & one public key type, 'PublicKey`. This enables users to be able to save & load secret keys using `StaticSecret` & allows us to use the same logic to create `PublicKey`s from both secret key types. 
In a key exchange, you don't have a way to know whether or not they'll ever reuse their secret key. Since creating a `PublicKey` is a conversion from a secret key, this name better reflects that the value might not be ephemeral.
> Static secret keys

- README.md
This PR changes the installation instructions to version ^0.5 & removes some trailing whitespace in the README.
> Doc version bump to 0.5

- src/x25519.rs
I ran into this issue in practice. My use case: I have a TreeKEM tree of private keys that needs updating, but the update operation is fallible. So I run the update on a clone of the tree, and if it fails, I rollback and delete the clone.
> Made StaticSecret cloneable

- src/x25519.rs
The `clone` inside `clamp_scalar` seems to to have no use and might lead to a situation where the StaticSecret remains in memory after dropping it since the original byte-array is not cleared.
> Ensure that all data of StaticSecret is cleared on drop

- Cargo.toml
- benches/x25519.rs
- src/x25519.rs
Start of adding support for serde serialize and deserialize
> WIP: support for serde serialize and deserialize

- Cargo.toml
- src/lib.rs
- src/x25519.rs
This PR removes the use of `clear_on_drop` and 
replaces it with [`zeroize`](https://docs.rs/zeroize/0.5.2/zeroize/). The switch to use `zeroize` would be
nice because the crate has nicer documentation and platform
support. This PR depends on https://github.com/dalek-cryptography/curve25519-dalek/pull/236 
and should change the`Cargo.toml` to use a newer version 
of `curve25519-dalek` if this change is accepted. 
Currently the `Cargo.toml` has a git dependency on the 
branch I implemented the `Zeroize` traits for `Scalar` 
and `MontgomeryPoint` on.
> Use zeroize crate

- Cargo.toml
- benches/x25519.rs
- src/lib.rs
- src/x25519.rs
This PR bumps the rand_core version.
This work follows from https://github.com/dalek-cryptography/x25519-dalek/pull/45 with attribution and this PR was made instead because it would've been more difficult to get that branch updated to merge it cleanly.
> Bump rand_core Version

- README.md
The `crypto_box` crate provides a pure Rust implementation of the public-key authenticated encryption primitive from NaCl which combines X25519 + XSalsa20Poly1305 (a.k.a. "Curve25519XSalsa20Poly1305")
This commit adds a link to it case x25519-dalek users are interested in using it as part of a hybrid cryptosystem.
> README.md: Add "See also" section with link to `crypto_box` crate

- Cargo.toml
Note this allows the use of benchmark comparison tooling such as [critcmp](https://github.com/BurntSushi/critcmp).
> Bump criterion version

- src/x25519.rs
Added so that `x25519_dalek::PublicKey` has the same as_bytes/to_bytes fns as `ed25519_dalek::PublicKey`
Also added `.to_bytes()` to `SharedSecret` for consistency.
> Add .to_bytes() to PublicKey, SharedSecret

- README.md
- src/x25519.rs
Closes #59.
The doc examples have code interspersed with text explaining the API.  Because
each doctest executes independently, when these code examples are run as
doctests, they have to include parts of the previous examples with # lines.
These lines are hidden from Rustdoc output and do not appear in the rendered
docs, but they do appear when viewing the README.md on Github.
In order to hide these on Github, the code blocks were made non-executable,
with their content moved to a unit test.  However, this meant that the example
API usage was not tested, and so when the unit test was updated to remove the
deprecated `rand_os`, there was no check that the examples stayed in sync with
the test, causing #59.  To prevent this from reocurring in the future, go back
to executable tests of the …
> Remove rand os example

- src/x25519.rs
Also does a pass through the docs converting `TypeNames` to Rustdoc links, and
making sure that all the items have consistent summaries.
Closes #58
Closes #56
> Clarify Ephemeral/StaticSecret docs.

- Cargo.toml
This allows unifying dependencies with other crates using the `3.x` series of
the curve library.  It is a semver patch-level change, because the x25519-dalek
API does not expose any details of the underlying curve implementation.
> Update curve25519-dalek to version 3.0.0.

- src/x25519.rs
Adds PartialEq, Eq, and Hash to derive statement for PublicKey.
Derives from the PartialEq impl for MontgomeryPoint.
Seemed like this was an easy win so users of this crate can use the PartialEq derive macro on structs that use PublicKey!
> Add PartialEq derive to PublicKey

- src/x25519.rs
Adding documentation example for bare byte API, as per https://github.com/dalek-cryptography/x25519-dalek/issues/30.
> Added doc example for x25519()

- Cargo.toml
This allows the fiat backends introduced in [curve25519-dalek/#342](https://github.com/dalek-cryptography/curve25519-dalek/pull/342) to be used from an x25519 import without cumbersome overrides.
> Threads the `fiat_{u32,u64}_backend` features through the feature set

- Cargo.toml
- src/x25519.rs
This implements secret keys which are technically reusable, but discouraged from reuse due to not having serialisation methods, in order to facilitate certain keying constructs in the Noise protocol and others which require doing Diffie-Hellman operations more than once with a single somewhat-ephemeral key. (cf. #57)
> Implement reused secret keys for Noise/X3DH/etc protocols

- Cargo.toml
https://github.com/rust-random/rand/blob/master/rand_core/CHANGELOG.md
This new version makes using rand_core on wasm seamless (thanks to the update of getrandom to v0.2)
The crate compiles well with this PR, but since some rand_core traits are publicly exposed in this crate's API, this is strictly speaking a breaking change.
> Update rand_core to 0.6

- Cargo.toml
- src/lib.rs
- src/x25519.rs
Fixes https://github.com/dalek-cryptography/x25519-dalek/issues/111
Move the get_random weak feature under rand_core as dev-dependency so we don't bring std that it brings.
Repeat of #112 due to release/2.0 branch got nuked
> Fix `no std` by moving `get_random` feat dev-deps

- Cargo.toml
- README.md
- benches/x25519.rs
- src/lib.rs
- src/x25519.rs
- tests/x25519_tests.rs
Fixes #85 
Supercedes #103 by re-rolling the commit with Co-authored-by @cipriancraciun (it was targeting main branch)
Provides the new feature `getrandom` with convenience `random_from_rng()` functions (naming aligned to other daleks)
Old PR was - release/2.0 branch got nuked: https://github.com/dalek-cryptography/x25519-dalek/pull/113
> Add `getrandom`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/x25519.rs
- tests/x25519_tests.rs
This removes all uses of `Scalar::[from_bits, from_bits_clamped}`. Some comments inline.
I'll update the git dependency once https://github.com/dalek-cryptography/curve25519-dalek/pull/519 drops.
> Update to new `Scalar` API

- README.md
The current `crypto_box` link returns a 404, RustCrypto moved it to a new `nacl-compat` repository. Thanks for the library!
> Update `crypto_box` URL

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- curve25519 rc.3: https://github.com/dalek-cryptography/curve25519-dalek/pull/535
- ed25519 rc.3: https://github.com/dalek-cryptography/ed25519-dalek/pull/307
- Obviously tests fail until curve25519 rc.3 out
- Lock needs to be updated when curve25519 rc.3 out
> chore: Release 2.0.0-rc.3
